package by.zvezdina.bodyartsalon.controller.command;

public enum CommandType {

    CHANGE_LOCALE,
    SIGN_IN,
    LOGOUT,
    SIGN_UP,
    VERIFY,

    SHOW_ALL_JEWELRY,
    ADD_JEWELRY,
    EDIT_JEWELRY,
    GO_TO_EDIT_JEWELRY,
    DELETE_JEWELRY,
    RESTORE_JEWELRY,

    SHOW_ALL_FACILITIES,
    DELETE_FACILITY,
    RESTORE_FACILITY,
    GO_TO_EDIT_FACILITY,
    EDIT_FACILITY,
    ADD_FACILITY,

    SHOW_ALL_ORDERS,
    OPEN_ORDER,
    ADD_ITEM_TO_BASKET,
    SHOW_BASKET,
    CREATE_ORDER,
    RECOUNT_ORDER_WHILE_ADDING_ITEM,
    RECOUNT_ORDER_WHILE_REMOVING_ITEM,
    SHOW_ORDERS_BY_CLIENT,
    CANCEL_ORDER,
    MARK_ORDER_AS_RECEIVED,

    UPDATE_PASSWORD,
    UPDATE_PROFILE,
    GO_TO_UPDATE_PROFILE,
    SHOW_ALL_USERS,
    DELETE_USER,
    RESTORE_USER,
    OPEN_PROFILE,
    CHANGE_CLIENT_DISCOUNT,

    TOP_UP_BALANCE,
    GO_TO_MAKE_APPOINTMENT,
    MAKE_APPOINTMENT,
    SHOW_ALL_RELEVANT_APPOINTMENTS_BY_PIERCER,
    OPEN_SINGLE_APPOINTMENT,
    SHOW_APPOINTMENTS_FOR_TODAY,
    SHOW_ALL_RELEVANT_APPOINTMENTS_BY_CLIENT,
    SHOW_ALL_APPOINTMENTS_BY_ADMIN,
    CANCEL_APPOINTMENT,

    SHOW_ALL_ACTIVE_PIERCERS,
    ADD_ADMIN,
    ADD_PIERCER,
    GO_TO_EDIT_PIERCER_WORKING_INFO,
    EDIT_PIERCER_WORKING_INFO,

    NOT_FOUND_PAGE,
}
