package by.zvezdina.bodyartsalon.controller.command;

public enum CommandType {

    CHANGE_LOCALE,
    SIGN_IN,
    LOGOUT,
    SIGN_UP,
    VERIFY,

    SHOW_ALL_JEWELRY,
    ADD_JEWELRY,
    EDIT_JEWELRY,
    GO_TO_EDIT_JEWELRY,
    DELETE_JEWELRY,
    RESTORE_JEWELRY,

    SHOW_ALL_FACILITIES,
    DELETE_FACILITY,
    RESTORE_FACILITY,
    GO_TO_EDIT_FACILITY,
    EDIT_FACILITY,
    ADD_FACILITY,

    SHOW_ALL_ORDERS,
    OPEN_ORDER,
    ADD_ITEM_TO_BASKET,
    SHOW_BASKET,
    CREATE_ORDER,
    RECOUNT_ORDER_WHILE_ADDING_ITEM,
    RECOUNT_ORDER_WHILE_REMOVING_ITEM,

    UPDATE_PASSWORD,
    UPDATE_PROFILE,
    GO_TO_UPDATE_PROFILE,
    SHOW_ALL_USERS,
    DELETE_USER,
    RESTORE_USER,
    OPEN_PROFILE,
    CHANGE_CLIENT_DISCOUNT,

    TOP_UP_BALANCE,

    MAKE_APPOINTMENT,

    DEFAULT
}
